# Generated by Django 5.1 on 2024-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
