# Generated by Django 5.1 on 2024-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_inquiry_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='called_received_by',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
