# Generated by Django 5.1 on 2024-09-12 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_inquiry_called_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('cheque_number', models.CharField(max_length=50)),
                ('cheque_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cheque_date', models.DateField()),
                ('mit', models.CharField(max_length=255)),
                ('reminder_email', models.EmailField(max_length=254)),
                ('extra_reminder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
