# Generated by Django 5.1 on 2024-09-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_cheque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='mit',
            new_name='cheque_miti',
        ),
    ]
