# Generated by Django 5.1 on 2024-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_rename_mit_cheque_cheque_miti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='handled_by',
            field=models.CharField(max_length=255),
        ),
    ]
