# Generated by Django 5.1 on 2024-09-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_cheque_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='diposited',
            field=models.BooleanField(default=False),
        ),
    ]
