# Generated by Django 5.1 on 2024-09-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_cheque_diposited'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='pending_status',
            field=models.BooleanField(default=True),
        ),
    ]
