# Generated by Django 5.1 on 2024-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_remove_inquiry_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('on_progress', 'On Progress'), ('reverted', 'Reverted'), ('confirmed', 'Confirmed'), ('sold', 'Sold'), ('not_fixed', 'Not Fixed'), ('declined', 'Declined'), ('mood_changed', 'Mood Changed'), ('others', 'Others')], default='new', max_length=20),
        ),
    ]
