# Generated by Django 5.1 on 2024-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='miti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
