# Generated by Django 5.1.4 on 2025-01-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0021_publicuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicUser',
        ),
    ]
