# Generated by Django 5.1.4 on 2024-12-17 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_event'),
        ('userauths', '0019_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_notes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crm_notes',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauths.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crm_notes',
            name='note_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crm_notes',
            name='note_title',
            field=models.CharField(max_length=200),
        ),
    ]
